[app]
name = "BeHome"
version = 1.0

[guard]
users = ["test"]
passwords = ["1234"]

[device]
arduinoPort = "/dev/ttyUSB0"

[output]
names = ["Название1", "Название2", "Название3", "Название4"]
pins = [2,3,4,5]